Feature/update dialogs layout
netigenkluzowicz/api_android pull request #161
Opened 2020-01-14 08:24 UTC by rogalz

RateUs:
- convert to Kotlin,
- remove unnecessary methods,
- update views, 
- remove old rate_us layouts and drawables.

Update layouts for: tranlations, gdpr

-add translations to api,
-create missing_strings file (unused strings from strings.xml) ,
- remove upper_case strings - use textAllCaps instead,

Its tested as SNAPSHOT in Best Level (portrait) and in Best Piano (landscape)

2020-01-14 08:48 UTC, michal-bogucki requested changes

2020-01-14 08:48 UTC, michal-bogucki commented on core/src/main/java/pl/netigen/core/language/ChangeLanguageDialogFragment.java
> +    private void setButtonsBackgroundTints() {//there is ext for tint
add context to variable

2020-01-14 08:48 UTC, michal-bogucki commented on core/src/main/java/pl/netigen/core/gdpr/GDPRDialogFragment.kt
> +            buttonYes.background.setTint(it, R.color.dialog_accent_netigen_api, PorterDuff.Mode.MULTIPLY)
_netigen_api ???

2020-01-14 08:48 UTC, michal-bogucki commented on core/src/main/res/drawable/background_header_gdpr.xml
> +    <solid android:color="@color/dialog_accent_netigen_api" />
_netigen_ipa

2020-01-14 10:12 UTC, Micpol approved these changes

2020-01-14 10:12 UTC, Micpol commented on core/src/main/java/pl/netigen/core/gdpr/GDPRDialogFragment.kt
> +
Why do you need a 2 enters here?

2020-01-14 10:12 UTC, Micpol commented on core/src/main/java/pl/netigen/core/gdpr/GDPRDialogFragment.kt
> +        return if (context != null) {
Why not wrap it with context?.let { } block?

2020-01-14 10:12 UTC, Micpol commented on core/src/main/java/pl/netigen/core/rateus/RateUsListener.kt
> +
It might be better to use lambdas instead of a callback interface

2020-01-14 10:12 UTC, Micpol commented on core/src/main/res/layout-h360dp-land/dialog_fragment_change_language.xml
> +    android:maxWidth="280dp"
Could be moved to layout_width and layout_height.

2020-01-14 10:12 UTC, Micpol commented on core/src/main/res/layout-land/dialog_fragment_rate_us_netigen_api.xml
> +        android:id="@+id/rateUsImage"
It PROBABLY would be better to remove dimensions ratio and add proper width

2020-01-14 10:12 UTC, Micpol commented on core/src/main/res/layout/dialog_fragment_rate_us_netigen_api.xml
> +        android:textColor="#535368"
You should extract this color m8

2020-01-14 10:13 UTC, Micpol requested changes
Consider all the comments I wrote, remember about styling and values extraction.

2020-01-17 05:40 UTC, Micpol approved these changes

2020-01-17 07:17 UTC, michal-bogucki approved these changes

2020-01-17 07:20 UTC, merged